name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
      run: |
        cd client
        npm install
        npm run build
      env:
        CI: true
    - name: deploy
      uses: maddox/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets. TADEUS_UBERSPACE_SSH_KEY }}
      with:
        args: npm run deploy
